sudo: required
conditions: v1
language: go
services:
  - docker
  - mongodb
go:
  - 1.10.x
env:
  - DEBUG=1 TESTING=1
before_script:
  - |
    mongo ss --eval 'db.createUser({
        user:"root",
        pwd:"root",
        roles:["readWrite"]
      });'
jobs:
  include:
    # run unit tests
    - stage: test
      name: tests
      script:
        - go test -v -race ./server
    # deploy only if on one of the main branches
    # - master is the latest public/live/production version
    # - staging is the next stable public/live/production version
    # - develop is the rolling development release version
    - stage: deploy
      name: deploy
      if: branch IN (master, staging, develop)
      script:
        - make static
        - docker build -t temp .
        - docker tag temp southclaws/tw-warehouse:$TRAVIS_BRANCH
        - docker push southclaws/tw-warehouse:$TRAVIS_BRANCH
        - docker tag temp southclaws/tw-warehouse:$TRAVIS_TAG
        - docker push southclaws/tw-warehouse:$TRAVIS_TAG
