sudo: required
conditions: v1
language: go
go:
  - 1.10.x
services:
  - docker
  - mongodb
env:
  - DEBUG=1 TESTING=1
before_script:
  - |
    mongo ss --eval 'db.createUser({
        user:"root",
        pwd:"root",
        roles:["readWrite"]
      });'
jobs:
  include:
    - stage: test
      name: tests
      script:
        - go test -v -race ./server
    - stage: deploy
      name: build
      script:
        - echo $TRAVIS_BRANCH
        - make static
    - if: branch IN (master, staging, develop)
      name: deploy
      script:
        - docker build -t temp .
        - docker tag temp southclaws/tw-warehouse:$TRAVIS_BRANCH
        - docker push southclaws/tw-warehouse:$TRAVIS_BRANCH
        - docker tag temp southclaws/tw-warehouse:$TRAVIS_TAG
        - docker push southclaws/tw-warehouse:$TRAVIS_TAG
