language: go
go:
  - 1.10.x
services:
  - mongodb
before_script:
  - |
    mongo ssc --eval 'db.createUser({
        user:"root",
        pwd:"root",
        roles:["readWrite"]
      });'
script:
  - go test -v -race ./server
