language: go
go:
  - 1.10.x
env:
  - DEBUG=1
  - TESTING=1
services:
  - mongodb
before_script:
  - |
    mongo ss --eval 'db.createUser({
        user:"root",
        pwd:"root",
        roles:["readWrite"]
      });'
script:
  - go test -v -race ./server
